version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.18.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea        
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:3000"
      - "2221:22"

    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql
  
  drone:      
    image: drone/drone:2
    restart: always
    environment:
      - DRONE_GITEA_SERVER=http://192.168.158.111:8080
      - DRONE_GITEA_CLIENT_ID=fb562c95-8a34-4348-8153-8bde2f4c6fc4
      - DRONE_GITEA_CLIENT_SECRET=gto_p5uooy3nga55vvufm63zxt6c6igirncshp6wluxes2byzn3a2sua
      - DRONE_RPC_SECRET=super-duper-secret
      - DRONE_SERVER_HOST=192.168.158.111
      - DRONE_SERVER_PROTO=http
    ports:
      - "80:80"
      - "443:443"  
    depends_on:
      - server
    networks:
      - gitea
    volumes:
      - ./drone:/data

  drone-runner-docker:
    image: drone/drone-runner-docker:1
    restart: always
    environment:
       - DRONE_RUNNER_CAPACITY=2
       - DRONE_RUNNER_NAME=drone-docker-runner
       - DRONE_RPC_SECRET=super-duper-secret
       - DRONE_RPC_HOST=192.168.158.111
       - DRONE_RPC_PROTO=http   
    ports:
      - "3000:3000"
    depends_on:
      - drone      
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  drone-runner-ssh:
     image: drone/drone-runner-ssh
     restart: always
     environment:
        - DRONE_RPC_SECRET=super-duper-secret
        - DRONE_RPC_HOST=192.168.158.111
        - DRONE_RPC_PROTO=http
     ports:
       - "3000:3000"
     depends_on:
       - drone      
     volumes:
       - "/var/run/docker.sock:/var/run/docker.sock"        














